lexik_jwt_authentication:
    secret_key: '%kernel.project_dir%/config/jwt/private.pem'
    public_key: '%kernel.project_dir%/config/jwt/public.pem'
    pass_phrase: '%env(JWT_PASSPHRASE)%'
    token_ttl: 3600

    set_cookies:
        BEARER:
            path: /
            domain: null
            httpOnly: true
            samesite: strict   # ✅ valeur en minuscule
            secure: auto
    
    token_extractors:
        cookie:
            enabled: true
            name: BEARER          # même nom que le cookie
        authorization_header:     # on peut garder l’en-tête aussi
            enabled: true
            prefix: Bearer
        query_parameter:
            enabled: false