security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: username

    firewalls:
        # Ressources statiques du dev-server
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # ← Intercepte UNIQUEMENT /api/login_check
        login:
            pattern: ^/api/login_check
            stateless: true
            json_login:
                check_path: /api/login_check      # même URL
                username_path: username           # champs que tu envoies
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        # Toutes les autres routes /api/** nécessitent le JWT
        api:
            pattern: ^/api
            stateless: true
            jwt: ~

        # Pour les pages « classiques » (twig…) si besoin
        main:
            lazy: true
            provider: app_user_provider

    access_control:
        - { path: ^/register,        roles: PUBLIC_ACCESS }
        - { path: ^/api/login_check, roles: PUBLIC_ACCESS }
        - { path: ^/api/admin,       roles: ROLE_ADMIN }
        - { path: ^/api,             roles: IS_AUTHENTICATED_FULLY }
